#!/usr/bin/env node
/**
 * Afterimage — build.
 *
 * theme.css is the shipped artifact and is hand-authored, EXCEPT for the
 * regions between BUILD: markers, which this script owns:
 *
 *   BUILD:FONTS     @font-face block, base64-embedded from fonts/
 *   BUILD:ARTWORK   new-tab artwork, embedded from assets/
 *   BUILD:VERSION   the version string in the header comment
 *
 * Everything travels inside theme.css as a data: URI because Obsidian
 * injects the theme as an inline <style>, so a relative url() cannot
 * resolve to a file in the theme folder.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const p = (...x) => path.join(ROOT, ...x);
const CHECK = process.argv.includes('--check');

const manifest = JSON.parse(fs.readFileSync(p('manifest.json'), 'utf8'));
const pkg = JSON.parse(fs.readFileSync(p('package.json'), 'utf8'));

/* ── Font set ────────────────────────────────────────────────────────────
   `family` is the name theme.css refers to. Every file here is recorded in
   FONT_LICENSES.md; scripts/audit.mjs cross-checks the two.               */
const FONTS = [
  { family: 'Afterimage VGA',   file: 'oldschool-pc-font-pack/WebPlus_IBM_VGA_9x16.woff', format: 'woff',
    style: 'normal', weight: '400', note: 'VileR · CC BY-SA 4.0 · unmodified' },
  { family: 'Afterimage VGA N', file: 'oldschool-pc-font-pack/WebPlus_IBM_VGA_8x16.woff', format: 'woff',
    style: 'normal', weight: '400', note: 'VileR · CC BY-SA 4.0 · unmodified' },
  { family: 'Afterimage 3270',  file: '3270font/3270-Regular.woff2', format: 'woff2',
    style: 'normal', weight: '400', note: '3270font Authors · BSD-3-Clause · transcoded to woff2' },
];
const LATIN = 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';
const EXT = 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF';
for (const [f, style, weight] of [['Regular','normal','400'],['Bold','normal','700'],['Italic','italic','400']]) {
  for (const [sub, range] of [['latin', LATIN], ['ext', EXT]]) {
    FONTS.push({ family: 'Courier Prime', file: `courier-prime/CourierPrime-${f}.${sub}.woff2`,
      format: 'woff2', style, weight, unicodeRange: range,
      note: 'Courier Prime Project Authors · SIL OFL 1.1 · unmodified (from Bureau)' });
  }
}

function fontFaceBlock() {
  const out = [
`/* BUILD:FONTS:START — generated by scripts/build.mjs; do not edit by hand.
   Every face is base64-embedded so the theme is offline-proof and never blocks
   first paint on a network fetch, and because Obsidian injects theme.css as an
   inline <style>, where a relative url() cannot resolve to a theme-folder file.

   LICENCES — full record in FONT_LICENSES.md:
     Afterimage VGA / VGA N  WebPlus IBM VGA 9x16 / 8x16, from The Ultimate
                             Oldschool PC Font Pack v2.2, (c) 2016-2020 VileR,
                             CC BY-SA 4.0 <creativecommons.org/licenses/by-sa/4.0/>.
                             SHIPPED UNMODIFIED — byte-identical to VileR's own
                             distribution, so no Adapted Material is produced and
                             ShareAlike attaches to these files, not to theme.css.
     Afterimage 3270         3270font v3.0.1, (c) 2011-2022 Ricardo Banffy and the
                             3270font Authors, BSD-3-Clause. Transcoded ttf -> woff2;
                             no glyph, metric or name-table change.
     Courier Prime           v3.018, (c) 2015 The Courier Prime Project Authors,
                             SIL OFL 1.1. Unmodified; inherited from Bureau. */`];
  let total = 0;
  for (const f of FONTS) {
    const abs = p('fonts', f.file);
    if (!fs.existsSync(abs)) throw new Error(`missing font file: fonts/${f.file}`);
    const b64 = fs.readFileSync(abs).toString('base64');
    total += b64.length;
    out.push(
`@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: block;${f.unicodeRange ? `\n  unicode-range: ${f.unicodeRange};` : ''}
  /* ${path.basename(f.file)} — ${f.note} */
  src: url(data:font/${f.format};base64,${b64}) format('${f.format}');
}`);
  }
  out.push(`/* BUILD:FONTS:END — ${FONTS.length} faces, ${(total/1024).toFixed(1)} KB base64 */`);
  return { text: out.join('\n'), bytes: total };
}

function artworkBlock() {
  const svg = fs.readFileSync(p('assets/new-tab.svg'), 'utf8').split(/\s+/).join(' ').trim();
  const uri = encodeURIComponent(svg)
    .replace(/%20/g, ' ').replace(/%3D/g, '=').replace(/%3A/g, ':').replace(/%2F/g, '/')
    .replace(/%22/g, "'").replace(/%7B/g, '{').replace(/%7D/g, '}').replace(/%3B/g, ';')
    .replace(/%2C/g, ',');
  return `/* BUILD:ARTWORK:START — generated from assets/new-tab.svg */
body {
  --after-new-tab-default-image: url("data:image/svg+xml,${uri}");
}
/* BUILD:ARTWORK:END — ${(uri.length/1024).toFixed(1)} KB */`;
}

function replaceRegion(src, name, replacement) {
  const re = new RegExp(`/\\* BUILD:${name}:START[\\s\\S]*?BUILD:${name}:END[^*]*\\*/`, 'm');
  if (!re.test(src)) throw new Error(`BUILD:${name} markers not found in theme.css`);
  return src.replace(re, replacement);
}

let css = fs.readFileSync(p('theme.css'), 'utf8');
const before = css.length;

const fonts = fontFaceBlock();
css = replaceRegion(css, 'FONTS', fonts.text);
css = replaceRegion(css, 'ARTWORK', artworkBlock());

// version string in the header comment
css = css.replace(/(\/\* Afterimage — .*?· v)[0-9]+\.[0-9]+\.[0-9]+/, `$1${manifest.version}`);

// version consistency
const errs = [];
if (manifest.version !== pkg.version) errs.push(`manifest ${manifest.version} != package.json ${pkg.version}`);
const versions = JSON.parse(fs.readFileSync(p('versions.json'), 'utf8'));
if (!versions[manifest.version]) errs.push(`versions.json has no entry for ${manifest.version}`);
else if (versions[manifest.version] !== manifest.minAppVersion)
  errs.push(`versions.json[${manifest.version}]=${versions[manifest.version]} != minAppVersion ${manifest.minAppVersion}`);
if (errs.length) { errs.forEach(e => console.error(`  ✗ ${e}`)); process.exit(1); }

const existing = fs.readFileSync(p('theme.css'), 'utf8');
if (CHECK) {
  if (existing !== css) { console.error('  ✗ theme.css is stale — run `npm run build`'); process.exit(1); }
  console.log('  ✓ theme.css is up to date'); process.exit(0);
}
fs.writeFileSync(p('theme.css'), css);
console.log(`  ✓ fonts     ${FONTS.length} faces, ${(fonts.bytes/1024).toFixed(1)} KB base64`);
console.log(`  ✓ artwork   embedded from assets/new-tab.svg`);
console.log(`  ✓ version   ${manifest.version} (minApp ${manifest.minAppVersion})`);
console.log(`  ✓ theme.css ${(before/1024).toFixed(1)} KB → ${(css.length/1024).toFixed(1)} KB`);
